version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
